botones:
	python3 botones.py

test:
	python3 testBotones.py 

grafico:
	python3 grafico.py

test:
	python3 testGrafico.py 

all:
	@echo "Compilación y ejecución de la práctica"

clean:
	@echo "Limpiando..."
